# Generated by Django 4.2.1 on 2023-05-15 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0003_skill_vacancy_skill'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vacancy',
            old_name='skill',
            new_name='skills',
        ),
    ]
